### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by pulyaevskiy** [Drakirus/go-flutter-desktop-embedder#1]
First of, thanks for sharing your work! It's great to see another approach available.

In readme you mentioned MacOS support is planned. Wondering what's the state on this front?

I'd like to explore this as well but have little knowledge of golang myself. It would be a lot easier for me to contribute when/if there is some scaffolding for macOS is in place already.

**Comment by Drakirus** [comment]
I haven't made any progress on the MacOS support.

I have pushed a new branch [#windows_build](https://github.com/Drakirus/go-flutter-desktop-embedder/compare/windows_build#diff-15924f74f29d8e395351e1372ced5b25). If you want to explore the implementation on MacOS, I encourage you to take a look at how it is done on windows and try to reproduce the same pattern on MacOS.

Most of it _should_ be in the [flutter/build.go](https://github.com/Drakirus/go-flutter-desktop-embedder/blob/master/flutter/build.go) file

**Comment by gedw99** [comment]
The Mac build should be pretty easy since you have Linux already.

Great that you already have a windows build. Will hack on both windows and Mac builds

**Comment by Drakirus** [comment]
This issues was definitely harder than expected.  
[d4df6def](https://github.com/Drakirus/go-flutter-desktop-embedder/commit/d4df6def83fded24ecfe83dc0f2f498331062715) add's the support the osx platform, a prebuild has been generated [v0.2.1-alpha](https://github.com/Drakirus/go-flutter-desktop-embedder/releases/tag/v0.2.1-alpha).

**Comment by pulyaevskiy** [comment]
Wow, just ran the stocks app, really nice. Thanks this is definitely a good starting point now.

**Comment by gedw99** [comment]
Great work @Drakirus !
This is really a game changer for me and many other Devs !!
