### ISSUE TITLE
memory leak in proxy_on_platform_messsage.

### ISSUE THREAD

**Issue by james-lawrence** [Drakirus/go-flutter-desktop-embedder#11]
see [documentation](https://github.com/flutter/engine/blob/080fbcb1759e5916f0d6cdcdfd945c053320e6b3/shell/platform/embedder/embedder.h#L91)
```golang
func proxy_on_platform_message(message *C.FlutterPlatformMessage, userPointer unsafe.Pointer) C.bool {
	if message.message != nil {
		str := C.GoString(C.converter(message.message, message.message_size))

		FlutterPlatformMessage := PlatformMessage{}

		messageContent := Message{}
		json.Unmarshal([]byte(str), &messageContent)

		FlutterPlatformMessage.Message = messageContent
		FlutterPlatformMessage.Channel = C.GoString(message.channel)
		if message.response_handle == nil {
			fmt.Println("==================== NIL")
		}

		return C.bool(globalFlutterOpenGL.FPlatfromMessage(FlutterPlatformMessage, userPointer))
	}
	return C.bool(false)

}
```

```golang
if message.response_handle == nil
```
should be 
```golang
FlutterPlatformMessage.ResponseHandle = (*platformMessageResponseHandle)(message.response_handle)
```

we would still need to handle the response later on but this moves the needle in the right direction.

**Comment by Drakirus** [comment]
For the keyboard input we have to ignore this field. 
The Doc says:
> This field is ignored for messages being sent from the embedder to the framework

And since we are using `FlutterEngineSendPlatformMessage` (Can send multiple messages) and not `FlutterEngineSendPlatformMessageResponse`(Can send ONE message for One response), this is not a memory leak.
