### ISSUE TITLE
build on windows failed

### ISSUE THREAD

**Issue by vjeson** [Drakirus/go-flutter-desktop-embedder#30]
go version : go1.11.2 windows/amd64

# github.com/Drakirus/go-flutter-desktop-embedder/flutter
..\..\..\github.com\Drakirus\go-flutter-desktop-embedder\flutter\flutter.go:200:17: cannot use _Ctype_ulong(len(data)) (type _Ctype_ulong) as type _Ctype_ulonglong in argument to func literal

**Comment by Drakirus** [comment]
Does the fix works ?
