### ISSUE TITLE
Error running go get -u -v github.com/Drakirus/go-flutter-desktop-embedder

### ISSUE THREAD

**Issue by Fireprufe15** [Drakirus/go-flutter-desktop-embedder#34]
When I attempt to run go get -u -v github.com/Drakirus/go-flutter-desktop-embedder on Windows, following your instructions, I get the following error:

c:/winbuilds/bin/../lib64/gcc/x86_64-w64-mingw32/4.8.3/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lflutter_engine
collect2.exe: error: ld returned 1 exit status

I did run the flag command from your instructions first.
Am I doing something wrong?

**Comment by Drakirus** [comment]
When you run `go get -u -v github.com/Drakirus/go-flutter-desktop-embedder` golang will try to compile the project. (Surely  for casing purposes)

So it's doesn't mater if it fail during `go get`.

Does the error occurs when building the `simpleDemo` ?

**Comment by Fireprufe15** [comment]
Yeah the same problem happens when I run go build.

I did set the path in the main.go file, maybe I did it wrong though?
Is it supposed to be 
gutter.OptionICUDataPath("/opt/flutter/bin/cache/artifacts/engine/windows-x64/icudtl.dat"),
or 
gutter.OptionICUDataPath("/flutter/bin/cache/artifacts/engine/windows-x64/icudtl.dat"),

Neither of those work for me. Do I need to set it to some specific path on my PC?

**Comment by Drakirus** [comment]
`gutter.OptionICUDataPath` is used at run time, so the error doesn't come from here.

The linker dosn't seems to find the `flutter_engine.dll` , can you try referencing that dll, or putting the dll into the mingw64's libs path.

**Comment by Fireprufe15** [comment]
Yeah throwing it in with the mingw64 libs seems to work. Thanks.

**Comment by Drakirus** [comment]
The generated binary, uses the `flutter_engine.dll` located right next to it.
The project should stay portable. And the `flutter_engine.dll` in the mingw64 libs is only used for compiling.

**Comment by mdcfrancis** [comment]
If you are using powershell you have to use a different syntax ` $env:CGO_LDFLAGS = "-LC:\......\simpleDemo"` allows me to compile.
