### ISSUE TITLE
Unable to build on Windows 10

### ISSUE THREAD

**Issue by Syleron** [Drakirus/go-flutter-desktop-embedder#44]
I get the following when attempting to run build simpleDemo:

..\..\flutter\flutter.go:177: cannot use C.uintptr_t(len(strMessage)) (type C.uintptr_t) as type C.size_t in field value

**Comment by Syleron** [comment]
I've managed to get it working by changing it to the expected C.size_t, however, unsure if this is the proper fix.

**Comment by Drakirus** [comment]
@Syleron thanks for the issue :smile: 
This is the proper fix! ref: [embedder.h](https://github.com/Drakirus/go-flutter-desktop-embedder/blob/140562ebcb093712e527a080bf32241f39c6f5e5/flutter/library/flutter_embedder.h#L90)
Do you think you could submit a quick PR for this?

**Comment by Syleron** [comment]
Awesome :) Yes, It's awaiting your confirmation.
