### ISSUE TITLE
how can i write a "mian.go" and a "pubspec.lock"?

### ISSUE THREAD

**Issue by winner484** [Drakirus/go-flutter-desktop-embedder#52]
## Flutter version 1.0.0

Thanks for your work than makes me successfully build the demo to a linux app.
But if i want to build a app for my own flutter project, how can i write a "mian.go" and the "pubspec.lock"?
I am new to go-lang as well as flutter.
can anybody tell me how to start?
Thanks a lot!

**Comment by Drakirus** [comment]
First of:
```The README has a little arrow next to the Operating system that shows build instructions when you click on the OS.```

Next up:
In the file [simpleDemo/main.go](https://github.com/Drakirus/go-flutter-desktop-embedder/blob/1a6f12721c313651a991e148d33b379d5969acd2/example/simpleDemo/main.go#L33-L42), you have the specify the path to the flutter's build using `gutter.ProjectAssetPath`

Finally:
On the flutter side, the only requirement is to run `flutter build bundle` which will generate you the `build/flutter_assets` directory. Directory to use in `gutter.ProjectAssetPath`

**Comment by winner484** [comment]
> First of:
> `The README has a little arrow next to the Operating system that shows build instructions when you click on the OS.`
> 
> Next up:
> In the file [simpleDemo/main.go](https://github.com/Drakirus/go-flutter-desktop-embedder/blob/1a6f12721c313651a991e148d33b379d5969acd2/example/simpleDemo/main.go#L33-L42), you have the specify the path to the flutter's build using `gutter.ProjectAssetPath`
> 
> Finally:
> On the flutter side, the only requirement is to run `flutter build bundle` which will generate you the `build/flutter_assets` directory. Directory to use in `gutter.ProjectAssetPath`

it`s ok with simpleDemo.
but i get this error when i use a hello_world project.
..............
$ go get -u -v github.com/Drakirus/go-flutter-desktop-embedder
github.com/Drakirus/go-flutter-desktop-embedder (download)
github.com/go-gl/glfw (download)
runtime/cgo
# runtime/cgo
gcc: error: (copy): No such file or directory
