### ISSUE TITLE
Keyboard layout

### ISSUE THREAD

**Issue by zephylac** [Drakirus/go-flutter-desktop-embedder#53]
## Flutter version
```
Flutter 1.0.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (2 weeks ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
```

## Does the prebuilt and portable version works ?
Yes

###### Download [Link](https://github.com/Drakirus/go-flutter-desktop-embedder/releases)
 - [ ] Yes
 - [X] No

## Steps to Reproduce

`glfw.SetKeyCallback` doesn't support keyboard layout. It only support US layout. [Documentation](https://www.glfw.org/docs/latest/group__input.html#ga7e496507126f35ea72f01b2e6ef6d155).
Whereas `glfwSetCharCallback`will support layout
This has for consequence to miss understand event but since we get actual key value from `glfwSetCharCallback` you will write what your keyboard is supposed to write.

For example if you have an AZERTY keyboard. When pressing A, glfw.keyQ event will be recorded but `glfwCharCallback` will know you are under another layout and will write A to your screen.
This problem breaks shortcuts under all operating system.

**Comment by Drakirus** [comment]
I reviewed your works!

**Comment by zephylac** [comment]
#57
