### ISSUE TITLE
mac: wrong directory

### ISSUE THREAD

**Issue by mikowiec** [Drakirus/go-flutter-desktop-embedder#55]
## Precondition

- macOS Sierra
- dart v2.1.0 installed via brew, flutter SDK not installed
- prebuild binary v0.3.0-alpha from github

## Does the prebuilt and portable version works ?
No

###### Download [Link](https://github.com/Drakirus/go-flutter-desktop-embedder/releases)
 - [x] Yes
 - [ ] No

## Steps to Reproduce

1. Unzip downloaded binary
2. Run `stocks`
3. Console shows error:
`2018/12/24 08:40:03 stat /Users/tbrocherieux/Downloads/stocks-example-GoFlutter_OSX/flutter_project/stocks/build/flutter_assets: no such file or directory`
```

**Comment by Drakirus** [comment]
Luckly the `main.go` used to compile the `stocks` binary is still in the zip file.
The `main.go` file wasn't compile with the correct go file.

@zephylac can you rebuild the stocks example using the simpler [stocks/main.go](https://github.com/Drakirus/go-flutter-desktop-embedder/blob/master/example/stocks/main.go)
Thanks :+1:

**Comment by zephylac** [comment]
ASAP 👍

**Comment by zephylac** [comment]
I've updated the release, it should work now. If you can check it on your side @mikowiec, it would be great.

**Comment by mikowiec** [comment]
not fixed

```log
Last login: Mon Dec 24 09:01:22 on ttys000
/Users/xxx/Downloads/stocks-example-GoFlutter_OSX/stocks ; exit;
➜  ~ /Users/xxx/Downloads/stocks-example-GoFlutter_OSX/stocks ; exit;
2018/12/27 09:46:50 stat flutter_project/stocks/build/flutter_assets: no such file or directory

[Process completed]
```

**Comment by zephylac** [comment]
It's working but for this release you need to execute it from the directory. When it was compiled, it was with 
` gutter.ProjectAssetPath("flutter_project/stocks/build/flutter_assets"),`
As this is not an absolute path (we would fall in the other case where absolute path is written in the executable), you need to execute it from it's directory otherwise he won't find `flutter_assets` directory
```
cd /Users/xxx/Downloads/stocks-example-GoFlutter_OSX
./stocks
```

**Comment by Drakirus** [comment]
I just ran into the following issue:
```
2018/12/27 09:33:48 stat /opt/flutter/bin/cache/artifacts/engine/darwin-x64/icudtl.dat: no such file or directory
```
@zephylac can you build the stocks example while making sure the path to the `gutter.ApplicationICUDataPath` is local to the `zip`
Thanks :+1:

**Comment by mikew** [comment]
In the meantime:

```sh
cd ~/Downloads/stocks-example-GoFlutter_OSX/FlutterEmbedder.framework/Versions
ln -sf A Current
cd ~/Downloads/stocks-example-GoFlutter_OSX/FlutterEmbedder.framework
ln -sf Versions/Current/Resources Resources
ln -sf Versions/Current/Modules Modules
ln -sf Versions/Current/Headers Headers
ln -sf Versions/Current/FlutterEmbedder FlutterEmbedder
```

**Comment by zephylac** [comment]
New release! 😀
