### ISSUE TITLE
Video Player Plugin

### ISSUE THREAD

**Issue by Syleron** [Drakirus/go-flutter-desktop-embedder#66]
I'm attempting to use the video_player plugin but it doesn't appear to instalize.

Is this plugin supported? If not, when can I expect this to work as it is a crucial part to my project.

Thank you.

**Comment by Drakirus** [comment]
The plugin architecture isn't ready to support Android/iOS plugins without to write/rewrite some Dart code, this goes against the Flutter philosophy and that why work on the plugin system needs to be done [#35](https://github.com/Drakirus/go-flutter-desktop-embedder/issues/35#issuecomment-443377193).

About the video_player, this kind of plugin needs access to the Texture widget. I strongly encourage you to read the following issue: [google/flutter-desktop-embedding #107](https://github.com/google/flutter-desktop-embedding/issues/107).

The google/flutter-desktop-embedding project is updated more frequently than this one, check them out!

**Comment by Syleron** [comment]
@Drakirus Thank you for this. I will have a closer look and see.

**Comment by gedw99** [comment]
There is a Flutter Plugin that uses Video that works on Mobiles and Desktop.
https://github.com/cloudwebrtc/flutter-webrtc-demo
https://github.com/cloudwebrtc/flutter-desktop-embedding

They also need Desktop and so have forker the official Flutter Desktop to add it.
How that affects the go-flutter-desktop-embedder i am not sure, but i suspect it will mean that the Desktop embedder will get it and so we can use it.
But i have not had time to dig into their fork enough, so just wanted to highlight it here for others.

**Comment by Drakirus** [comment]
#134
